- README.md
> Update README.md - corrects doc link

- cmd/flawfind/main.go
- cmd/flawfix/api/api.go
- internal/core/asset/asset_controller.go
- internal/core/asset/dependency_tree.go
- internal/core/asset/dependency_tree_test.go
- internal/core/flaw/flaw_controller.go
- internal/core/flaw/flaw_dto.go
- internal/core/vulndb/scan/cpe_comparer.go
- internal/core/vulndb/scan/purl_comparer.go
- internal/core/vulndb/scan/sbom_scanner.go
- internal/core/vulndb/scan/scan_controller.go
- internal/database/models/component_model.go
- internal/database/repositories/asset_repository.go
- internal/database/repositories/flaw_repository.go
- internal/obj/asset_obj.go
- internal/utils/concurrency.go
> Adds a dependency graph to flawfix

- cmd/devguard-scanner/commands/sca.go
- cmd/devguard/api/api.go
- cmd/devguard/main.go
- internal/core/assetversion/asset_version_controller.go
- internal/core/assetversion/asset_version_service.go
- internal/database/repositories/asset_version_repository.go
Added the Interface to delete a given asset version from the database
> 264 delete asset version

- cmd/devguard-scanner/commands/sca.go
Added the panic instead of returning
> When a new Sca Command Fails it now panics instead of resolving as usual

- cmd/devguard/api/api.go
- cmd/devguard/api/api_test.go
- internal/accesscontrol/casbin_rbac.go
- internal/core/assetversion/asset_version_controller.go
- internal/core/common_interfaces.go
- internal/core/context_utils.go
- internal/core/integrations/github_integration.go
- internal/core/integrations/gitlab_integration.go
- internal/core/org/org_controller.go
- internal/core/project/project_controller.go
- internal/core/project/project_service.go
Changed all tenants to organizations
Changed all c to ctx
> Banished all tenants and (almost) all  'c' variable names  from the Code

- cmd/devguard-scanner/commands/sarif.go
> removed the info logging in sarif.go

- internal/database/models/first_party_vuln_model.go
- internal/database/models/first_party_vuln_test.go
moved the line of code into the link and wrote 100% T T T T TEST COVERAAAGE!!!!! 😎 🔥 😮‍💨 🤯
> 604 first party vuln tickets have the wrong filelink the line should actually be included in the link

- cmd/devguard/api/api.go
- internal/core/common_interfaces.go
- internal/core/statistics/statistics_asset_controller.go
- internal/database/repositories/statistics_repository.go
Added a function for retrieving all CVEs with an existing exploit for a given assetVersion.
> 535 add information about the amount of vulnerabilities with known exploits to the dashboard

- internal/core/org/org_dto.go
- internal/database/models/org_model.go
- internal/utils/common.go
I have a feeling I missed a few lines of code which might need to be changed to use languages
> 611 add language column to organization   we might need to translate created GitHub and gitlab tickets

- internal/core/assetversion/asset_version_service.go
- internal/database/models/asset_version_model.go
Added new column to assetversion Model and changed the assigment of the old values to work with the new json
> 626 replace multiple scan timestamp columns with unified json field

- .vscode/launch.json
- cmd/devguard/api/api.go
- docker-compose.yaml
- internal/core/assetversion/asset_version_service.go
- internal/core/daemon/scan_daemon.go
- internal/database/models/dependency_vuln_model.go
- internal/database/models/vulnevent_model.go
- internal/database/repositories/dependency_vuln_repository.go
Implements https://github.com/l3montree-dev/devguard/issues/645
> add support for lastUpdated and firstIssued dates

- cmd/devguard-scanner/commands/sca.go
This changes resolves issue #688
> Removing URL column

- internal/core/integrations/gitlabint/gitlab_integration.go
Webhook is now created without uncessary privileges
> disabled push events in the webhook options

- cmd/devguard-scanner/commands/root.go
- cmd/devguard-scanner/commands/slug.go
added slug command to the devguard scanner command palette
> added slug command

- internal/core/assetversion/asset_version_service.go
changed the sbom.json generation to be sound with the cdx standard
working on the sbom.xml
> sbom are now validated by the cdx validater

- .github/workflows/devguard-scanner.yaml
- cmd/devguard-scanner/commands/sbom.go
- cmd/devguard-scanner/commands/sca.go
- cmd/devguard-scanner/config/config.go
related: https://github.com/l3montree-dev/devguard-action/pulls
> add fail-on-cvss option to scanning configuration

- Dockerfile
- charts/devguard/values.yaml
- docker-compose-try-it.yaml
…improves docker compose try it
> Sets nonroot user for devguard api image, in helm default values and improves docker compose try it

- internal/core/integrations/commonint/integration_helper.go
- internal/core/integrations/commonint/integration_helper_test.go
closes https://github.com/l3montree-dev/devguard/issues/980
> streamline label extraction logic 

- cmd/devguard-scanner/commands/sarif.go
- internal/database/models/first_party_vuln_model.go
- internal/database/models/first_party_vuln_test.go
Added dynamic syntax highlighting based off the file extension 
Fixed link to file and added lines to the description
Improved the looks of the tickets
> 982 need tabs and line numbers in snippets

- internal/core/assetversion/asset_version_service.go
- internal/core/vuln/license_risk_service.go
Fixed component dependencies creation when updating sboms
Added state diff handling for license risks
> Fix dependecnies and license risks

- internal/core/asset/asset_service.go
- internal/core/project/project_service.go
close https://github.com/l3montree-dev/devguard/issues/1088 https://github.com/l3montree-dev/devguard/issues/1023
> correct asset activation logic in CreateAsset method

- internal/core/integrations/githubint/github_integration.go
- internal/core/integrations/gitlabint/gitlab_handle_event.go
- internal/core/integrations/jiraint/jira_handle_event.go
close https://github.com/l3montree-dev/devguard/issues/1161
> enhance comment formatting in GitHub, GitLab, and Jira integrations

- cmd/devguard-scanner/commands/container_scanning.go
- cmd/devguard-scanner/commands/iac.go
- cmd/devguard-scanner/commands/sarif.go
- cmd/devguard-scanner/commands/sast.go
- cmd/devguard-scanner/commands/sbom.go
- cmd/devguard-scanner/commands/sca.go
- cmd/devguard-scanner/commands/secret_scanning.go
close https://github.com/l3montree-dev/devguard/issues/1228
> update add scan flags functions
